---
# This is a CI workflow that is designed to test the end-to-end behaviour
# of a stack deployed to the designated installation (a Kubernetes cluster).
# The tests rely on Ansible "Job Templates" that are available on
# a designates AWX server.
#
# The test assumes: -
#
# - The cluster exists
# - Job Templates exist
# - The repository has environment-based secrets under the name 'awx/fragalysis-developer'
#   That are named: -
#   - AWX_E2E_USER_PASSWORD
#
# This workflow only runs if vars.TEST_E2E_ENABLED is set to "yes"

name: test stack e2e

on: push

env:
  # AWX host and user.
  # Password is provided in an environment secret (AWX_E2E_USER_PASSWORD)
  AWX_HOST: https://awx.xchem-dev.diamond.ac.uk
  AWX_E2E_USER: simona
  # Job Template names
  AWX_E2E_JT_NAME_WIPE: User (Simona) Developer Fragalysis Stack [WIPE]
  AWX_E2E_JT_NAME_DEPLOY: User (Simona) Developer Fragalysis Stack
  AWX_E2E_STACK_IMAGE_TAG: latest

jobs:
  gate:
    runs-on: ubuntu-latest
    if: ${{ vars.TEST_E2E_ENABLED == 'yes' }}
    steps:
      - run: echo "Enabled"

  wipe:
    needs: gate
    runs-on: ubuntu-latest
    environment: awx/fragalysis-developer
    steps:
      - name: Wipe the test stack
        uses: informaticsmatters/trigger-awx-action@v4
        with:
          template: ${{ env.AWX_E2E_JT_NAME_WIPE }}
          template-host: ${{ env.AWX_HOST }}
          template-user: ${{ env.AWX_E2E_USER }}
          template-user-password: ${{ secrets.AWX_E2E_USER_PASSWORD }}

  deploy:
    needs: wipe
    runs-on: ubuntu-latest
    environment: awx/fragalysis-developer
    steps:
      - name: Deploy the (clean) test stack
        uses: informaticsmatters/trigger-awx-action@v4
        with:
          template: ${{ env.AWX_E2E_JT_NAME_DEPLOY }}
          template-host: ${{ env.AWX_HOST }}
          template-user: ${{ env.AWX_E2E_USER }}
          template-user-password: ${{ secrets.AWX_E2E_USER_PASSWORD }}
          template-var: stack_image_tag
          template-var-value: ${{ env.AWX_E2E_STACK_IMAGE_TAG }}

  test:
    needs: deploy
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CYPRESS_LOGIN: ${{ secrets.AWX_E2E_CYPRESS_LOGIN }}
      CYPRESS_PASSWORD: ${{ secrets.AWX_E2E_CYPRESS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Install dependencies
        run: npm install
      - name: Install Cypress binary
        run: npx cypress install
      - name: Verify Cypress
        run: npx cypress verify
        
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          install: false
          build: npm run build
          start: npm start
          # browser: chrome
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      - name: Upload junit reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: junit-reports
          path: report*.xml
          if-no-files-found: ignore
